name: Leapp Publish

on:
  push:
    branches:
      - own-build
  workflow_dispatch:
    inputs:
      linux:
        description: "Publish linux packages"
        required: false
        type: boolean
      mac:
        description: "Publish mac packages"
        required: false
        type: boolean
      windows:
        description: "Publish windows packages"
        required: false
        type: boolean
      
jobs:
  changes:
    name: 'Inspect changes'
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.filter.outputs.core }}
      cli: ${{ steps.filter.outputs.cli }}
      desktop-app: ${{ steps.filter.outputs.desktop-app }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: HEAD
        filters: |
          core:
            - 'packages/core/**'
          cli:
            - 'packages/cli/**'
          desktop-app:
            - 'packages/desktop-app/**'
  

  publish_linux:
    name: 'Publish linux'
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' || needs.changes.outputs.cli == 'true' || needs.changes.outputs.desktop-app == 'true' || (always() && github.event.inputs.linux == 'true') }}
    strategy:
      matrix:
        #os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ ubuntu-latest ]
        node_version: [ 16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare GIT
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Setup NPM
        env:
          JF_USER: ${{ secrets.JF_SECRET_USER }}
          JF_API_KEY: ${{ secrets.JF_SECRET_API_KEY }}
          JF_HOST: ${{ secrets.JF_SECRET_HOST }}
          JF_REPO: ${{ secrets.JF_SECRET_REPO }}
        run: |
          curl -u $JF_USER:$JF_API_KEY https://$JF_HOST/artifactory/api/npm/auth/ -o ~/.npmrc
          echo "registry=https://$JF_HOST/artifactory/api/npm/$JF_REPO/" >> ~/.npmrc
      - name: Bootstrap
        run: |
          npm install
      - name: Build core
        run: |
          cd packages/core
          npm install
          eval curVer=$(npm pkg get version)
          eval gitHash=$(git rev-parse --short HEAD)
          npm pkg set version=$curVer-$gitHash.$GITHUB_RUN_ATTEMPT-linux
          npm run build
      - name: Build and publish cli
        run: |
          cd packages/cli
          npm install ../core
          eval curVer=$(npm pkg get version)
          eval gitHash=$(git rev-parse --short HEAD)
          npm pkg set version=$curVer-$gitHash.$GITHUB_RUN_ATTEMPT-linux
          npm run release-npm
      - name: Build and publish desktop-app
        env:
          JF_USER: ${{ secrets.JF_SECRET_USER }}
          JF_API_KEY: ${{ secrets.JF_SECRET_API_KEY }}
          JF_HOST: ${{ secrets.JF_SECRET_HOST }}
          JF_BIN_REPO: ${{ secrets.JF_SECRET_BIN_REPO }}
        run: |
          cd packages/desktop-app
          npm install ../core
          eval curVer=$(npm pkg get version)
          eval gitHash=$(git rev-parse --short HEAD)
          npm pkg set version=$curVer-$gitHash.$GITHUB_RUN_ATTEMPT-linux
          npm pkg delete build.publish
          npm run release-linux
          rm -Rf ./release/linux-unpacked ./release/.cache ./release/builder-debug.yml ./release/builder-effective-config.yaml ./release/.icon-set ./release/latest-linux.yml
          ls -la ./release
          curl -u $JF_USER:$JF_API_KEY -T release/Leapp-$curVer-$gitHash.$GITHUB_RUN_ATTEMPT-linux.AppImage https://$JF_HOST/artifactory/$JF_BIN_REPO/
          curl -u $JF_USER:$JF_API_KEY -T release/Leapp_$curVer-$gitHash.$GITHUB_RUN_ATTEMPT-linux_amd64.deb https://$JF_HOST/artifactory/$JF_BIN_REPO/

  publish_windows:
    name: 'Publish windows'
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' || needs.changes.outputs.cli == 'true' || needs.changes.outputs.desktop-app == 'true' || (always() && github.event.inputs.windows == 'true') }}
    strategy:
      matrix:
        os: [ windows-latest ]
        node_version: [ 16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare GIT
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Setup NPM
        env:
          JF_USER: ${{ secrets.JF_SECRET_USER }}
          JF_API_KEY: ${{ secrets.JF_SECRET_API_KEY }}
          JF_HOST: ${{ secrets.JF_SECRET_HOST }}
          JF_REPO: ${{ secrets.JF_SECRET_REPO }}
        run: |
          $secPass = ConvertTo-SecureString $env:JF_API_KEY -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($env:JF_USER, $secPass)
          Invoke-WebRequest -Credential $cred -Uri https://$env:JF_HOST/artifactory/api/npm/auth/ -OutFile $env:USERPROFILE\.npmrc
          Add-Content $env:USERPROFILE\.npmrc "registry=https://$env:JF_HOST/artifactory/api/npm/$env:JF_REPO/"
      - name: Bootstrap
        run: |
          npm install
      - name: Build core
        run: |
          cd packages/core
          npm install
          $curVer = (npm pkg get version).Trim('"')
          $gitHash = (git rev-parse --short HEAD)
          npm pkg set version=$curVer-$gitHash.$env:GITHUB_RUN_ATTEMPT-win
          npm run build
      - name: Build and publish cli
        run: |
          cd packages/cli
          npm install ../core
          $curVer = (npm pkg get version).Trim('"')
          $gitHash = (git rev-parse --short HEAD)
          npm pkg set version=$curVer-$gitHash.$env:GITHUB_RUN_ATTEMPT-win
          npm run release-npm
      - name: Build and publish desktop-app
        env:
          JF_USER: ${{ secrets.JF_SECRET_USER }}
          JF_API_KEY: ${{ secrets.JF_SECRET_API_KEY }}
          JF_HOST: ${{ secrets.JF_SECRET_HOST }}
          JF_BIN_REPO: ${{ secrets.JF_SECRET_BIN_REPO }}
          WIN_CSC_KEY_UUCONTENT: ${{ secrets.WIN_CSC_KEY_UUCONTENT }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
        run: |
          cd packages/desktop-app
          npm install ../core
          $curVer = (npm pkg get version).Trim('"')
          $gitHash = (git rev-parse --short HEAD)
          npm pkg set version=$curVer-$gitHash.$env:GITHUB_RUN_ATTEMPT-win
          npm pkg delete build.publish
          [System.Convert]::FromBase64String($env:WIN_CSC_KEY_UUCONTENT:) | Set-Content windows_sign_certificate.pfx -Encoding byte
          npm run release-win
          #rm -Rf ./release/linux-unpacked ./release/.cache ./release/builder-debug.yml ./release/builder-effective-config.yaml ./release/.icon-set ./release/latest-linux.yml
          Get-ChildItem release
          $secPass = ConvertTo-SecureString $env:JF_API_KEY -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($env:JF_USER, $secPass)
          Invoke-RestMethod -Method Put -Credential $creds -InFile .\release\Leapp-$curVer-$gitHash.$env:GITHUB_RUN_ATTEMPT-win.zip -Uri https://$env:JF_HOST/artifactory/$env:JF_BIN_REPO/Leapp-$curVer-$gitHash.$env:GITHUB_RUN_ATTEMPT-win.zip